### PR TITLE
WPP-66, fix URLRewritingFilter to prevent blank src attribute being a…

### PR DESCRIPTION
**Pull request by romandgood**
…dded to script tags when no src present.

Also added some tests to cover the script parsing. Added a ProxyControllerTest which tests a few filters together in combination.

### CODE REVIEW

**Comment by bjagg** [comment]
Hi Richard, did you hear anything about your iCLA submission?

Also, the imports should follow the code standard: https://wiki.jasig.org/display/UPM42/JetBrains+IntelliJ , for example

**Comment by bjagg** [comment]
https://issues.jasig.org/browse/WPP-66

**Comment by ChristianMurphy** [comment]
@bjagg it looks like the iCLA has posted

**Comment by ChristianMurphy** [comment]
Hey @romandgood, thanks for the pull request!
Unfortunately this PR appears to have stalled.
I'm going to close this PR, feel free to re-open it if you have time to resolve the changes requested

**Pull request closed without merging**
