### PR TITLE
Add support for Cosign proxy authentication

### PR DESCRIPTION
**Pull request by rnicoll**
The University of Edinburgh has developed in-house support for proxy authentication using Cosign, and the code is now well tested and ready for submission back to the main project.

Notably, we've had to add-in support for injecting cookies into a Request, from a pre-interceptor; simply naively re-writing the cookies resulted in loss of cookies managed by WebProxyPortlet, and the most efficient solution seemed to be treat the new cookies as their own set. Any feedback on the design there would be welcomed.

### CODE REVIEW

**Comment by jameswennmacher** [comment]
Will need to look at this in regard to v2

**Comment by jameswennmacher** [comment]
Moved v2 to master, so this PR will have to be executed to the rel-1-patches branch.  Also should be incorporated into the (new v2) master.

**Comment by ChristianMurphy** [comment]
@rnicoll merge conflicts have cropped up, could you resolve them?

**Comment by rnicoll** [comment]
Unfortunately have since moved job a couple of times, and have no access to a current uPortal install, so would be rather impractical for me to rebuild the entire environment at this point.

**Comment by bjagg** [comment]
Closing PR without merging based on comments

**Pull request closed without merging**
